settings = {
   'additional-options' : '',
   'additional-options-enabled' : False,
   'audio-extract' : False,
   'audio-format' : 'mp3',
   'audio-formats' : ('best', 'aac', 'vorbis', 'mp3', 'm4a', 'opus', 'wav'),
   'auto-remove-log-at-close' : True,
   'cmd' : ['youtube-dl'],
   'debug-menu-enabled' : False,
   'height-cmd-args' : 3,
   'path-destination' : '/home/tub/data/accessories/desktop',
   'poll-interval-for-download-in-milli-seconds' : 500,
   'poll-interval-for-metainfo-in-milli-seconds' : 100,
   'startup-copy-to-clipboard' : None,
   'startup-paste-clipboard-to-source-url' : True,
   'subtitle-languages' : 'en,de',
   'subtitle-languages-auto-created' : 'en',
   'subtitles' : 'off',
   'subtitles-depend-on-audio-only' : False,
   'update-settings' : False,
   'video-format' : 'mp4',
   'video-format-explicit' : False,
   'video-formats' : ('mp4', 'flv', 'ogg', 'webm', 'mkv', 'avi'),
   'video-keep' : False,
   'width-cmd-args' : 50,
   'width-source-url' : 50,
   'width-subtitle-languages' : 15,
   'width-video-format' : 5,
   'width-working-dir' : 40,
}